name: 'data_lake_gold'
version: '1.0.0'
config-version: 2

profile: 'data_lake_gold'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_lake_gold:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    gold:
      +materialized: table
